### ISSUE TITLE
Description of LEDGER_URL

### ISSUE THREAD

**Issue by ii-nik** [hyperledger/aries-acapy-controllers#30]
https://github.com/hyperledger/aries-acapy-controllers/blob/809d1095e009da8fcfd2408140bbacd917c5d4d3/AliceFaberAcmeDemo/run_demo#L38

Tried to figure out how I could set LEDGER_URL to point to lets say Sovrin Staging Net. Without any success. The only thing I found would be to use https://github.com/sovrin-foundation/sovrin/tree/master/sovrin ... but not sure if it works and ifs a good idea either.

So, a description of how to use this env var would be very appreciated....

**Comment by swcurran** [comment]
The LEDGER_URL is a URL that returns the data of the genesis file for the ledger.

I think this should work for Sovrin staging.  It is the raw version of the file checked into GitHub.

https://raw.githubusercontent.com/sovrin-foundation/sovrin/master/sovrin/pool_transactions_sandbox_genesis

**Comment by ii-nik** [comment]
Hi swcurran

Hmm, I found genesis you mention in the URL. It's the following line which then brought me off track, because 

https://github.com/hyperledger/aries-acapy-controllers/blob/809d1095e009da8fcfd2408140bbacd917c5d4d3/AliceFaberAcmeDemo/run_demo#L39

GENESIS_URL="${LEDGER_URL}/genesis"

So, GENESIS_URL would point to https://raw.githubusercontent.com/sovrin-foundation/sovrin/master/sovrin/pool_transactions_sandbox_genesis/genesis which doesn't exist. 
I will try now first we a local vonx network what I know to work and then will try further again

**Comment by ii-nik** [comment]
... but thanks, acertain me that https://raw.githubusercontent.com/sovrin-foundation/sovrin/master/sovrin/pool_transactions_sandbox_genesis should be fine ;-)

**Comment by swcurran** [comment]
Ah, I think that you can use GENESIS_URL instead of LEDGER_URL as the environment variable to set.  That would then carry into the process and all would be well.

Now...having said all that -- you still can't use Sovrin Staging for this demo, as it has restrictions on who can write to that ledger.  You would have to have a pre-created DID for one, and you would have to acknowledge the TAA.  All of those things can be done with ACA-Py, but they are not built into the demo (and it doesn't make sense to add that support to this demo).

@alexgmetcalf, @esune -- something we need to add to the ACA-Py docs - how to deal with the TAA in a real ACA-Py deployment.  I know we've done it a lot, but I'm not sure it's documented.

**Comment by swcurran** [comment]
Closing this...please reopen if you have further questions.
