### ISSUE TITLE
Errors running on play with docker

### ISSUE THREAD

**Issue by ianco** [hyperledger/aries-acapy-controllers#6]
Tested locally and everything ran fine (ran the docker version).

Tried running on play with docker (http://play-with-von.vonx.io/) and had a few issues:

- ran a local von-network and the demo dockers in the same session
- couldn't create an invitation (got a "502 gateway error" from the create invitation service, http://ip10-1-50-4-boqas4dm4dlga5djnugg-8031.direct.play-with-von.vonx.io/connections/create-invitation on my pwv session)
- when I clicked on anything in the Acme session (in the browser) it re-directed to the Alice session

I suggest testing this on play with docker and see if you can reproduce the same results.  I chatted with stephen curran and he had different issues running under pwd ...

**Comment by amanji** [comment]
It appears this issue is specific to running the demos using [Play with VON](http://play-with-von.vonx.io), according to @swcurran? The recommendation was to run the demos instead using [Play with Docker](https://labs.play-with-docker.com) if choosing the [Run in a Browser](https://github.com/hyperledger/aries-acapy-controllers/tree/master/AliceFaberAcmeDemo#running-in-a-browser) method. The docs were recently [updated](https://github.com/hyperledger/aries-acapy-controllers/pull/14/commits/d7d5a2db71ddc6260c795d10495e5ad14001d060) to reflect this.

If there is a suitable workaround can this issue be closed?

**Comment by swcurran** [comment]
I think so. I'm sure it's an issue with PWV.
